######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 12 20:40:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += msdata.h mypainterwidget.h static_data.h textdata.h
SOURCES += msdata.cpp \
           mypainterwidget.cpp \
           static.cpp \
           static_data.cpp \
           textdata.cpp
