######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 17:14:35 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ctpclient.h mypainterwidget.h
SOURCES += ctpclient.cpp mainwindow.cpp real_file.cpp realtime.cpp ruptime.c
