######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 20:54:04 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += csimple_handler.h ctpclient.h mypainter.h mypainterwidget.h
SOURCES += csimple_handler.cpp \
           ctpclient.cpp \
           mainwindow.cpp \
           mypainter.cpp \
           mypainterwidget.cpp
